- name: “Install docker”
  hosts: all
  become: true
  vars:
    packages:
      - python3
      - python3-pip
      - python3-setuptools

   pip: packages:
      - six
      - docker
      - requests