- name: Install docker on hosts
  hosts: all
  become: true

  tasks:
  - name: Update packages
    apt:
      update_cache: yes

  - name: Install pip2
    apt:
      name: python-pip
      state: present

  - name: Install requests module
    become: true
    pip:
      name: requests
      executable: pip2

  - name: Install docker-py
    become: true
    pip:
      name: docker-py
      state: present

  - name: Ensure packages are present
    apt:
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
      state: present

  - name: Ensure docker is present
    apt:
      name: docker-ce
      state: present

  - name: Ensure docker is started
    service:
      name: docker
      state: started

- name: Build app
  hosts: build
  become: true

  tasks:
  - name: Copy Dockerfile into build node
    copy:
      src: Dockerfile
      dest: /home/dmitry

  - name: Build image
    docker_image:
      path: /home/dmitry
      name: buildappl8
      tag: latest

  - name: Login to Docker Hub
    docker_login:
      email: morgotq@gmail.com
      username: morgotq
      password: Zoipolidz1.

  - name: Tag image with Docker Hub repository name
    docker_image:
      name: buildappl8
      tag: latest
      repository: morgotq/buildappl8
      push: yes

- name: Run application in prod
  hosts: prod
  become: true

  tasks:
  - name: Pull Docker image from Docker Hub
    docker_image:
      name: morgotq/buildappl8
      tag: latest
  - name: Run Docker container
    docker_container:
      name: prod
      image: morgotq/buildappl8
      state: started
      ports:
        - "8085:8080"
